---
title: "Tuples"
subtitle: ""
excerpt: "Covers tuples as a fixed, unchangeable alternative to lists useful for data that shouldn't be modified, such as coordinates or fixed groupings of values."
date: 2026-09-01
author: "Kelvin Kiprono"
draft: false
# layout options: single, single-sidebar
layout: single
categories:
- Python
---
##What Is a Tuple?
The word tuple comes from mathematics, where it’s used to describe a finite ordered sequence of values.For example , (1,2,3) is a tuple containing three integers.
Tuples are ordered because their elements appear in an ordered fashion.

##How to Create a Tuple

There are a few ways to create a tuple in Python. We’ll cover two of
them:
1. Tuple literals
2. The built-in tuple()

#Tuple Literals

Just like a string literal is a string that is explicitly created by surrounding some text with quotes, a tuple literal is a tuple that is written out explicitly as a comma-separated list of values surrounded by parentheses.
Here’s an example of a tuple literal:
```{python}
my_first_tuple = (1, 2, 3)

```
Unlike strings, which are sequences of characters, tuples may contain any type of value, including values of different types. The tuple (1,
2.0, "three") is perfectly valid.

```{python}
my_next_tuple=(1,2,'three','Kelvin')
```
To create a tuple containing the single value 1, you need to include a comma after the 1:
```{python}
x=(1,)
type(x)
```

##The Built-In tuple()
You can also use the built-in tuple() to create a tuple from another sequence type, such as a string:
```{python}
tuple("Python")
```

